sudo: false
language: ruby

rvm:
- 2.7
- 2.6.5
- 2.6.2
- 2.6.1
- 2.5
- 2.4
- 2.3
- 2.2
- 2.1
- 2.0
- ruby-head
- jruby-9.2.9.0
- truffleruby

matrix:
  allow_failures:
    - rvm: jruby-2.9.2.0
    - rvm: truffleruby
#   fast_finish: true
